---
name: "GitHub Actions Example"

"on":
  pull_request:
  push: { branches: [marwa] }

jobs:
  deploy_terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_github_actor_username: ${{ github.actor }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Apply Mapping Rules
        run: |
          # Define the mapping JSON string
          MAP_JSON='{
            "marwaelayyadi": "123-",
            "y": "456-",
            "z": "789-"
          }'

          # Parse the JSON object and retrieve the mapped value
          MAPPED_USERNAME=$(echo "$MAP_JSON" | jq -r --arg input "$TF_VAR_github_actor_username" '.[$input // "default"]')

          # Combine the mapped value with the GitHub actor's username
          FINAL_USERNAME="${MAPPED_USERNAME}${TF_VAR_github_actor_username}"
          
          # Display the mapped username
          echo "Mapped GitHub Actor Username: $FINAL_USERNAME"
          
          # Set the mapped username as TF_VAR_github_actor_username
          echo "TF_VAR_github_actor_username=$FINAL_USERNAME" >> $GITHUB_ENV
      
      - name: Display GitHub Actor Username
        run: 'echo "GitHub Actor Username: $TF_VAR_github_actor_username"'